export const colors = {
  LIGHT_WHITE: '#FCFCFC',
  LIGHTER_GRAY: '#E5E5E5',
  DARK_GRAY: '#3D3D3D',
  LIGHT_GRAY_VARIATION: '#CFCFCF',
  BLACK_VARIATION: '#3E3E3E',
  ELCARHBA_YELLOW: '#F5A934',
  WHITE: '#FFFFFF',
  DARK_navy_BLUE: '#324A54',
  BLUE: '#6C63FF'
};
